homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.7029
  longitude: 2.4136
  # Impacts weather/sunrise data
  elevation: 33
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
#  customize: !include_dir_merge_named Customize
  
zone: !include zones.yaml  

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Show links to resources in log and frontend
#introduction:

http:
  # Uncomment this to add a password (recommended!)
  api_password: 2709

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Z68ZQO-if00-port0
  
light:
  - platform: rfxtrx
    automatic_add: True
  
switch:
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b110000003c3a220b010f70:
        name: Lumiere Salon
      0A14050D00282701010000:
        name: Lumiere Chambre 
cover:
  platform: rfxtrx
  automatic_add: True
  signal_repetitions: 1
  devices:
    071a000007270101: # RFY
      name: Volet Salon
    071a000007270201: # RFY
      name: Volet SAM
    071a000007270301: # RFY
      name: Volet Bureau
    071a000007270401: # RFY
      name: Volet Chambre
    071a000007270501: # RFY
      name: Volet Cuisine
    071a000007270601: # RFY
      name: Prise SAM      

    